name: Examples
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  examples:
    uses: status-im/nimbus-common-workflow/.github/workflows/common.yml@main
    with:
      test-command: |
       nimble c ./examples/poc_gossipsub.nim
       nimble c ./examples/poc_gossipsub_repeated_runs.nim
       nimble c ./examples/poc_noresp_ping.nim
